language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
install:
- npm install -g npx
- npm install
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: DWEZDoTmQ2zy9jqLVAQ2aA3sHWejtCcv4nalU9TsGGbVJKiokww3SZvTOUkElE533mjOf8qH3AWREU9wUINS1Pw/c7D6BPAEJ2jPiYxQ2YCwNXP4aXU+Tl0XVuyc79k67aMAtHGQxUbjD+7BqfYtBCmVVvDG+27kjc4fHsPg2rTQkckJP/qHU/rKkNzn69T/kcVYGOIUd2dVqIcMO6R3e6vcNdqViv1v45/1QuTYyMzxTXmza7+uGdq6uOjoqSyL21Ot3iacrSsL9/rkSOaiW48mqPAsUO6pLjhmbFBgKl0qOAl2Q917C1zJYzO0/GNC+3tdVFLqeIfpymtUNrwOP+OxWIJZExe/XRtQ39iy5O9lQJnlFt0R8Z4B798GZg3ruz/6buoTWALgQ8Z86/71m3SRHDgXJZCjUnXefxsStupT3CNON5cVxJjmmCmDIahXR3kND+3gLqDgdpvUmuw0R4wN0qFczSEMLEEXctOeTRuXfJQg9TiKbGt69kGafOQrVFte16KOLdQ9CI6YT7UZBJtMKPNXEEf24EHWSbqCO2mHfa2jE6LgweAaym0ArzsrfEq95FJlo5FwZWf8zAmjkL17Foowimt1Uiw4qTIAYrThIuWWIpPMVXQoe3O7v/q1DV2GttiqF+DcBQ2XhfzKafQBiMaCIlN+bkYKmZEadhw=
  app: SafeVPN-challenge
  on: master
